# Generated by Django 3.1.3 on 2020-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'verbose_name': 'Currency rate',
                'verbose_name_plural': 'Currency rates',
                'ordering': ('-date', 'currency'),
                'unique_together': {('currency', 'date')},
                'index_together': {('currency', 'date')},
            },
        ),
    ]
