# Generated by Django 5.2.17 on 2026-09-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rate',
            new_name='currencies__currenc_569347_idx',
            old_fields=('currency', 'date'),
        ),
    ]
