name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Python Django Coverage GitHub Action
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        django-app: 'eurate'
        minimum-coverage: '80'
